<?php

return [
    // Cavite Cities / Municipalities
    'cities' => [
        'Alfonso'                   => ['zip' => '4123'],
        'Amadeo'                    => ['zip' => '4119'],
        'Bacoor'                    => ['zip' => '4102'],
        'Carmona'                   => ['zip' => '4116'],
        'Cavite City'               => ['zip' => '4100'],
        'Dasmariñas'                => ['zip' => '4114'],
        'General Emilio Aguinaldo'  => ['zip' => '4124'],
        'General Mariano Alvarez'   => ['zip' => '4117'],
        'General Trias'             => ['zip' => '4107'],
        'Imus'                      => ['zip' => '4103'],
        'Indang'                    => ['zip' => '4122'],
        'Kawit'                     => ['zip' => '4104'],
        'Magallanes'                => ['zip' => '4113'],
        'Maragondon'                => ['zip' => '4112'],
        'Mendez'                    => ['zip' => '4151'],
        'Naic'                      => ['zip' => '4110'],
        'Silang'                    => ['zip' => '4118'],
        'Tagaytay'                  => ['zip' => '4120'],
        'Tanza'                     => ['zip' => '4108'],
        'Ternate'                   => ['zip' => '4111'],
        'Trece Martires'            => ['zip' => '4109'],
    ],

    'barangays' => [

        // ============================================================
        // ALFONSO
        // ============================================================
        'Alfonso' => [
            'Amayong',
            'Bilog-Bilog',
            'Esperanza Ibaba',
            'Esperanza Ilaya',
            'Luksuhin',
            'Luksuhin Ilaya',
            'Manggahan',
            'Marahan I',
            'Marahan II',
            'Marawa',
            'Pajo',
            'Panamitan',
            'Poblacion I',
            'Poblacion II',
            'Poblacion III',
            'Poblacion IV',
            'Poblacion V',
            'Poblacion VI',
            'San Jose',
            'San Pedro I',
            'San Pedro II',
            'Santa Catalina',
            'Santo Niño',
            'Sikat',
            'Sulucan',
            'Taywanak Ibaba',
            'Taywanak Ilaya',
            'Upli',
        ],

        // ============================================================
        // AMADEO
        // ============================================================
        'Amadeo' => [
            'Barangay I (Poblacion)',
            'Barangay II (Poblacion)',
            'Barangay III (Poblacion)',
            'Barangay IV (Poblacion)',
            'Barangay V (Poblacion)',
            'Barangay VI (Poblacion)',
            'Barangay VII (Poblacion)',
            'Barangay VIII (Poblacion)',
            'Barangay IX (Poblacion)',
            'Bucal',
            'Daine I',
            'Daine II',
            'Francisco I',
            'Francisco II',
            'Halang',
            'Lantic',
            'Maitim 1st',
            'Manggahan',
            'Mañaga',
            'Minantok Kanluran',
            'Minantok Silangan',
            'Pangil',
            'Pulong Saging',
            'Talon',
            'Tanaman',
            'Tibig',
        ],

        // ============================================================
        // BACOOR (complete)
        // ============================================================
        'Bacoor' => [
            'Alima',
            'Aniban I',
            'Aniban II',
            'Aniban III',
            'Aniban IV',
            'Aniban V',
            'Banalo',
            'Bayanan',
            'Campo Santo',
            'Daang Bukid',
            'Digman',
            'Dulong Bayan',
            'Habay I',
            'Habay II',
            'Kaingin',
            'Ligas I',
            'Ligas II',
            'Ligas III',
            'Mabolo I',
            'Mabolo II',
            'Mabolo III',
            'Maliksi I',
            'Maliksi II',
            'Maliksi III',
            'Molino I',
            'Molino II',
            'Molino III',
            'Molino IV',
            'Molino V',
            'Molino VI',
            'Molino VII',
            'Niog I',
            'Niog II',
            'Niog III',
            'Panapaan I',
            'Panapaan II',
            'Panapaan III',
            'Panapaan IV',
            'Panapaan V',
            'Panapaan VI',
            'Panapaan VII',
            'Panapaan VIII',
            'Queens Row Central',
            'Queens Row East',
            'Queens Row West',
            'Real I',
            'Real II',
            'Salinas I',
            'Salinas II',
            'Salinas III',
            'Salinas IV',
            'San Nicolas I',
            'San Nicolas II',
            'San Nicolas III',
            'Sineguelasan',
            'Springville',
            'Tabing Dagat',
            'Talaba I',
            'Talaba II',
            'Talaba III',
            'Talaba IV',
            'Talaba V',
            'Talaba VI',
            'Talaba VII',
            'Zapote I',
            'Zapote II',
            'Zapote III',
            'Zapote IV',
            'Zapote V',
        ],

        // ============================================================
        // CARMONA
        // ============================================================
        'Carmona' => [
            'Bancal',
            'Cabilang Baybay',
            'General Aguinaldo',
            'General Pio Del Pilar',
            'Gregorio',
            'Lantic',
            'Lourdes',
            'Maduya',
            'Milagrosa',
            'Poblacion',
        ],

        // ============================================================
        // CAVITE CITY
        // ============================================================
        'Cavite City' => [
            'Barangay 1 (San Jose)',
            'Barangay 2 (San Pedro)',
            'Barangay 3 (Santo Niño)',
            'Barangay 4 (San Roque)',
            'Barangay 5 (San Antonio)',
            'Barangay 6',
            'Barangay 7',
            'Barangay 8',
            'Barangay 9',
            'Barangay 10',
            'Barangay 11',
            'Barangay 12',
            'Barangay 13',
            'Barangay 14',
            'Barangay 15',
            'Barangay 16',
            'Barangay 17',
            'Barangay 18',
            'Barangay 19',
            'Barangay 20',
            'Barangay 21',
            'Barangay 22',
            'Barangay 23',
            'Barangay 24',
            'Barangay 25',
            'Barangay 26',
            'Barangay 27',
            'Barangay 28',
            'Barangay 29',
            'Barangay 30',
            'Caridad',
            'Dalahican',
            'Dominador I',
            'Dominador II',
            'Kababahan',
            'Kanlaon',
            'Pag-Asa I',
            'Pag-Asa II',
            'Pag-Asa III',
            'Pag-Asa IV',
            'Timalan Bayan',
            'Timalan Concepcion',
            'Wakas',
        ],

        // ============================================================
        // DASMARIÑAS (expanded)
        // ============================================================
        'Dasmariñas' => [
            'Bagong Bayan I-A',
            'Bagong Bayan I-B',
            'Bagong Bayan I-C',
            'Bagong Bayan I-D',
            'Bagong Bayan I-E',
            'Bagong Bayan I-F',
            'Bagong Bayan II-A',
            'Bagong Bayan II-B',
            'Bagong Bayan II-C',
            'Bagong Bayan II-D',
            'Burol I',
            'Burol II',
            'Burol III',
            'Langkaan I',
            'Langkaan II',
            'Luzviminda I',
            'Luzviminda II',
            'Paliparan I',
            'Paliparan II',
            'Paliparan III',
            'Salitran I',
            'Salitran II',
            'Salitran III',
            'Salitran IV',
            'Sampaloc I',
            'Sampaloc II',
            'Sampaloc III',
            'Sampaloc IV',
            'Sampaloc V',
            'San Agustin I',
            'San Agustin II',
            'San Agustin III',
            'San Miguel',
            'San Simon',
            'Santa Lucia',
            'Santa Maria',
            'Santo Cristo',
            'Victoria Reyes',
            'Zone I',
            'Zone II',
            'Zone III',
            'Zone IV',
        ],

        // ============================================================
        // GENERAL EMILIO AGUINALDO
        // ============================================================
        'General Emilio Aguinaldo' => [
            'Bailen',
            'Bucal',
            'Castaños',
            'Castaños Cerca',
            'Dos Cruses',
            'Kayquit I',
            'Kayquit II',
            'Kayquit III',
            'Luksuhin',
            'Maguyam',
            'Mamplasan',
            'Munting Mapino',
            'Orense',
            'Pasong Camachile',
            'Pasong Kawayan',
            'Poblacion I',
            'Poblacion II',
            'Pook ni Ramon',
            'Pulo',
            'San Miguel',
            'Santa Lucia',
            'Santiago',
            'Tabon I',
            'Tabon II',
            'Tibungol',
        ],

        // ============================================================
        // GENERAL MARIANO ALVAREZ (GMA)
        // ============================================================
        'General Mariano Alvarez' => [
            'Aldiano Olaes (Poblacion)',
            'Barangay 1 Kanluran',
            'Barangay 1 Silangan',
            'Barangay 2 Kanluran',
            'Barangay 2 Silangan',
            'Barangay 3-A',
            'Barangay 3-B',
            'Barangay 4-A',
            'Barangay 4-B',
            'Barangay 5-A',
            'Barangay 5-B',
            'Barangay 6-A',
            'Barangay 6-B',
            'Barangay 7-A',
            'Barangay 7-B',
            'Barangay 8-A',
            'Barangay 8-B',
        ],

        // ============================================================
        // GENERAL TRIAS (complete)
        // ============================================================
        'General Trias' => [
            'Alingaro',
            'Arnaldo',
            'Bacao I',
            'Bacao II',
            'Bagumbayan',
            'Biclatan',
            'Buenavista I',
            'Buenavista II',
            'Buenavista III',
            'Corregidor',
            'Dulong Bayan',
            'Gov. Ferrer',
            'Javalera',
            'Manggahan',
            'Navarro',
            'Ninety Sixth',
            'Panungyanan',
            'Pasong Camachile I',
            'Pasong Camachile II',
            'Pasong Kawayan I',
            'Pasong Kawayan II',
            'Pinagtipunan',
            'Prinza',
            'Sampalucan',
            'San Francisco',
            'San Gabriel',
            'San Juan I',
            'San Juan II',
            'Santa Clara',
            'Santiago',
            'Tapia',
            'Tejero',
            'Vibora',
        ],

        // ============================================================
        // IMUS (expanded)
        // ============================================================
        'Imus' => [
            'Alapan I-A',
            'Alapan I-B',
            'Alapan I-C',
            'Alapan II-A',
            'Alapan II-B',
            'Anabu I-A',
            'Anabu I-B',
            'Anabu I-C',
            'Anabu I-D',
            'Anabu I-E',
            'Anabu I-F',
            'Anabu I-G',
            'Anabu II-A',
            'Anabu II-B',
            'Anabu II-C',
            'Bayan Luma I',
            'Bayan Luma II',
            'Bayan Luma III',
            'Bayan Luma IV',
            'Bayan Luma V',
            'Bayan Luma VI',
            'Bayan Luma VII',
            'Bayan Luma VIII',
            'Bayan Luma IX',
            'Bucandala I',
            'Bucandala II',
            'Bucandala III',
            'Bucandala IV',
            'Bucandala V',
            'Carsadang Bago I',
            'Carsadang Bago II',
            'Magdalo (Poblacion)',
            'Malagasang I-A',
            'Malagasang I-B',
            'Malagasang I-C',
            'Malagasang I-D',
            'Malagasang I-E',
            'Malagasang I-F',
            'Malagasang I-G',
            'Malagasang II-A',
            'Malagasang II-B',
            'Malagasang II-C',
            'Malagasang II-D',
            'Malagasang II-E',
            'Malagasang II-F',
            'Malagasang II-G',
            'Medicion I-A',
            'Medicion I-B',
            'Medicion I-C',
            'Medicion I-D',
            'Medicion I-E',
            'Medicion I-F',
            'Medicion II-A',
            'Medicion II-B',
            'Medicion II-C',
            'Medicion II-D',
            'Medicion II-E',
            'Medicion II-F',
            'Medicion II-G',
            'Pasong Buaya I',
            'Pasong Buaya II',
            'Pinagbuklod',
            'Tanzang Luma I',
            'Tanzang Luma II',
            'Tanzang Luma III',
            'Tanzang Luma IV',
            'Tanzang Luma V',
            'Tanzang Luma VI',
            'Toclong I-A',
            'Toclong I-B',
            'Toclong I-C',
            'Toclong II-A',
            'Toclong II-B',
            'Tulong',
        ],

        // ============================================================
        // INDANG
        // ============================================================
        'Indang' => [
            'Agus-os',
            'Alulod',
            'Banaba Cerca',
            'Banaba Lejos',
            'Bancod',
            'Buna Cerca',
            'Buna Lejos I',
            'Buna Lejos II',
            'Calumpang Cerca',
            'Calumpang Lejos I',
            'Calumpang Lejos II',
            'Carasuchi',
            'Daine I',
            'Daine II',
            'Guyam Malaki',
            'Guyam Munti',
            'Harasan',
            'Kayquit',
            'Limbon',
            'Lumampong Balagbag',
            'Lumampong Halayhay',
            'Mahabang Kahoy Cerca',
            'Mahabang Kahoy Lejos',
            'Mataas na Lupa',
            'Pulo',
            'Poblacion I',
            'Poblacion II',
            'Poblacion III',
            'Tambo Balagbag',
            'Tambo Ilaya',
            'Tambo Kulit',
            'Tambo Malaki',
        ],

        // ============================================================
        // KAWIT
        // ============================================================
        'Kawit' => [
            'Balsahan',
            'Batong Dalig',
            'Binakayan',
            'Binakayan-Aplaya',
            'Gahak',
            'Kaingen',
            'Kapitan Mulong',
            'Magdalo',
            'Malagasang',
            'Manggahan',
            'Marulas',
            'Niog',
            'Pulvorista',
            'Putol',
            'Roberts',
            'Sabang',
            'San Carlos',
            'San Sebastian',
            'Santa Isabel',
            'Tatalon',
            'Tejero',
            'Wakas Norte',
            'Wakas Sur',
        ],

        // ============================================================
        // MAGALLANES
        // ============================================================
        'Magallanes' => [
            'Barangoon',
            'Bungahan',
            'Canonigo I',
            'Canonigo II',
            'Canonigo III',
            'Inagasan',
            'Lantic',
            'Magubat',
            'Manolaying',
            'Nagauayan',
            'Pacaña I',
            'Pacaña II',
            'Pinagsibaan',
            'Poblacion I',
            'Poblacion II',
            'Poctoy',
            'Pulangbato',
            'San Agustin',
            'Talaba',
            'Urdaneta',
            'Wakas',
        ],

        // ============================================================
        // MARAGONDON
        // ============================================================
        'Maragondon' => [
            'Bucal I',
            'Bucal II-A',
            'Bucal II-B',
            'Buho',
            'Caingin I',
            'Caingin II',
            'Garita I',
            'Garita II',
            'Haligue Kanluran I',
            'Haligue Kanluran II',
            'Haligue Silangan I',
            'Haligue Silangan II',
            'Layong Mabilog',
            'Mabato',
            'Norte I',
            'Norte II',
            'Pantihan I',
            'Pantihan II',
            'Pantihan III',
            'Pantihan IV',
            'Papaya',
            'Patungan',
            'Pinagsibaan',
            'Poblacion I',
            'Poblacion II',
            'Poblacion III',
            'Sapa',
            'Talim I',
            'Talim II',
            'Tulay Kanluran',
            'Tulay Silangan',
            'Wakas Kanluran',
            'Wakas Silangan',
        ],

        // ============================================================
        // MENDEZ (Méndez-Nuñez)
        // ============================================================
        'Mendez' => [
            'Anuling Cerca I',
            'Anuling Cerca II',
            'Anuling Lejos I',
            'Anuling Lejos II',
            'Batong Dalig',
            'Bukal',
            'Galicia I',
            'Galicia II',
            'Galicia III',
            'Galicia IV',
            'Galicia V',
            'Kaytapos',
            'Lucsuhin',
            'Panungyan',
            'Poblacion I',
            'Poblacion II',
            'Poblacion III',
            'Poblacion IV',
            'San Isidro',
            'San Juan I',
            'San Juan II',
            'San Marcos I',
            'San Marcos II',
            'Talon',
        ],

        // ============================================================
        // NAIC
        // ============================================================
        'Naic' => [
            'Balsahan',
            'Bancaan I',
            'Bancaan II',
            'Bucana',
            'Bubuyan',
            'Calubcob',
            'Caputatan Norte',
            'Caputatan Sur',
            'Gomez-Caluag',
            'Halang',
            'Humbac',
            'Ibayo Estero',
            'Ibayo Silangan',
            'Kanluran',
            'Labac',
            'Latoria',
            'Mabolo I',
            'Mabolo II',
            'Makina',
            'Malainen Bago',
            'Malainen Luma',
            'Molino',
            'Muzon',
            'Panamitan',
            'Poblacion I',
            'Poblacion II',
            'Poblacion III',
            'Sabang',
            'San Isidro',
            'San Jose',
            'Santulan',
            'Timalan',
            'Tuyeau',
        ],

        // ============================================================
        // SILANG
        // ============================================================
        'Silang' => [
            'Alitagtag',
            'Balite I',
            'Balite II',
            'Banaba',
            'Batas',
            'Buho',
            'Bulihan',
            'Can-Arangin',
            'Capipisa',
            'Cotcot',
            'Fatima',
            'Inchican',
            'Ipilan',
            'Kalayaan',
            'Kaong',
            'Lalaan I',
            'Lalaan II',
            'Litlit',
            'Lucsuhin',
            'Lumil',
            'Maguyam',
            'Malabag',
            'Malagasang',
            'Mataas na Burol',
            'Munting Ilog',
            'Niyugan',
            'Paligawan',
            'Poblacion I',
            'Poblacion II',
            'Pooc I',
            'Pooc II',
            'Putting Kahoy',
            'San Miguel I',
            'San Miguel II',
            'San Vicente I',
            'San Vicente II',
            'Santa Rosa I',
            'Santa Rosa II',
            'Tartaria',
            'Tibig',
            'Tribulan Cerca',
            'Tribulan Lejos',
            'Wakas I',
            'Wakas II',
            'Ynigo',
        ],

        // ============================================================
        // TAGAYTAY (complete)
        // ============================================================
        'Tagaytay' => [
            'Asisan',
            'Bagong Tubig',
            'Calabuso',
            'Dapdap East',
            'Dapdap West',
            'Francisco',
            'Guinhawa North',
            'Guinhawa South',
            'Iruhin Central',
            'Iruhin East',
            'Iruhin South',
            'Iruhin West',
            'Kaybagal Central',
            'Kaybagal North',
            'Kaybagal South',
            'Mag-Asawang Ilat',
            'Maharlika East',
            'Maharlika West',
            'Maitim 2nd Central',
            'Maitim 2nd East',
            'Maitim 2nd West',
            'Mendez Crossing East',
            'Mendez Crossing West',
            'Neogan',
            'Patutong Malaki North',
            'Patutong Malaki South',
            'Sambong',
            'San Jose',
            'Silang Crossing East',
            'Silang Crossing West',
            'Sungay East',
            'Sungay West',
            'Tolentino East',
            'Tolentino West',
            'Zambal',
        ],

        // ============================================================
        // TANZA
        // ============================================================
        'Tanza' => [
            'Amaya I',
            'Amaya II',
            'Amaya III',
            'Amaya IV',
            'Amaya V',
            'Amaya VI',
            'Amaya VII',
            'Bagong Bayan',
            'Biga I',
            'Biga II',
            'Biwas',
            'Bucal I',
            'Bucal II-A',
            'Bucal II-B',
            'Bunga I',
            'Bunga II',
            'Calibuyo',
            'Capipisa',
            'Daang Amaya I',
            'Daang Amaya II',
            'Daang Amaya III',
            'Halayhay',
            'Julugan I',
            'Julugan II',
            'Julugan III',
            'Julugan IV',
            'Julugan V',
            'Julugan VI',
            'Julugan VII',
            'Julugan VIII',
            'Lambingan',
            'Mulawin',
            'Natutunok',
            'Pag-Asa I',
            'Pag-Asa II',
            'Pantalan Bago',
            'Pantalan Luma',
            'Punta I',
            'Punta II',
            'Sahud Ulan',
            'Salapan',
            'San Isidro',
            'San Jose',
            'Santa Cruz',
            'Santo Cristo I',
            'Santo Cristo II',
            'Tanique',
            'Tres Cruses',
        ],

        // ============================================================
        // TERNATE
        // ============================================================
        'Ternate' => [
            'Bucana',
            'Calabuso',
            'Lalay',
            'Luka',
            'Mabilis',
            'Poblacion',
            'Punta',
            'San Juan I',
            'San Juan II',
            'San Juan III',
            'Santa Cecilia',
            'Zapang',
        ],

        // ============================================================
        // TRECE MARTIRES
        // ============================================================
        'Trece Martires' => [
            'Aguado',
            'Arnaldo',
            'Cabezas',
            'Cabuco',
            'De Ocampo',
            'Gregorio',
            'Hugo Perez',
            'Inocencio',
            'Kapit-Bahay (Poblacion)',
            'Luciano',
            'Osorio',
            'Perez',
            'Railroad',
            'San Agustin',
            'Tejero',
        ],

    ],
];
